/*
 * generated by Xtext
 */
package org.eclipselabs.mongo.query;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MongoSQLRuntimeModule extends org.eclipselabs.mongo.query.AbstractMongoSQLRuntimeModule {

}
