/*
* generated by Xtext
*/
package org.eclipselabs.mongo.query.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.mongo.query.services.MongoSQLGrammarAccess;

public class MongoSQLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MongoSQLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.mongo.query.parser.antlr.internal.InternalMongoSQLParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.mongo.query.parser.antlr.internal.InternalMongoSQLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MongoSQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MongoSQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
