INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('SYSTEM_ADMIN','System Admin');
INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('ADMIN','Admin');
INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('DBA','DBA');
INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('MANAGER','Manager');
INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('USER','User');
INSERT INTO tadpole_role(ROLE_ID, ROLE_NAME) VALUES ('GUEST', 'Guest')


INSERT INTO dbtype(TYPE_CODE, TYPE_NAME, SMALL_NAME) VALUES ('PRODUCTION','Production Sever', '');
INSERT INTO dbtype(TYPE_CODE, TYPE_NAME, SMALL_NAME) VALUES ('DEVELOP','Develop Sever', '');
INSERT INTO dbtype(TYPE_CODE, TYPE_NAME, SMALL_NAME) VALUES ('TEST','Test Sever', '');
INSERT INTO dbtype(TYPE_CODE, TYPE_NAME, SMALL_NAME) VALUES ('BACKUP','Backup Sever', '');
INSERT INTO dbtype(TYPE_CODE, TYPE_NAME, SMALL_NAME) VALUES ('OTHERS','Others Sever', '');
